### ISSUE TITLE
MongoDB warning on Travis

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/getting-started-php#107]
on Travis (see [this build](https://travis-ci.org/GoogleCloudPlatform/getting-started-php/jobs/110051836#L2401)):

```
PHP Warning:  Module 'mongodb' already loaded in Unknown on line 0
Warning: Module 'mongodb' already loaded in Unknown on line 0
```

This may be because the `mongodb` extension is already compiled into PHP, and we are also installing it in [.travis.yml](https://github.com/GoogleCloudPlatform/getting-started-php/blob/master/.travis.yml#L44) via `pecl`

**Comment by tmatsuo** [comment]
This is fine in my opinion. Travis doesn't guarantee the existence of the mongodb extension and I want to be resilient to their changes.

**Comment by bshaffer** [comment]
While I don't typically agree with fixing a problem before it exists, I've added a conditional so we can at least get rid of the warnings being thrown in our tests.
