### ISSUE TITLE
Invalid VM Runtime Specified

### ISSUE THREAD

**Issue by hepaestus** [GoogleCloudPlatform/getting-started-php#126]
I keep getting this error when I try to upload the code to the app engine:

me@big-bite: 1-hello-world$ appcfg.py -A my-hello-world -V v1 update ./
10:17 AM Application: my-hello-world (was: None); version: v1 (was: None)
10:17 AM Host: appengine.google.com
10:17 AM Starting update of app: pete-olsen-hello-world, version: v1
10:17 AM Getting current resource limits.
10:17 AM Scanning files on local disk.
Error 400: --- begin server output ---
Invalid VM runtime specified: php
--- end server output ---

**Comment by JustinBeckwith** [comment]
Greetings!  You can't use appcfg.py to deploy applications with App Engine Flexible.  You should use the [Cloud SDK](https://cloud.google.com/sdk/), and the `gcloud preview app deploy` command.  Check out the getting started guide here:

https://cloud.google.com/php/getting-started/hello-world

Hope this helps!
