### ISSUE TITLE
Bookshelf "Cloud Datastore" app doesn't deploy

### ISSUE THREAD

**Issue by avion-alter** [GoogleCloudPlatform/getting-started-php#152]
Hi ,

I am using '2-structured-data' folder code provided in Github. I am able to execute code to localhost and its storing the data to the datastore when making an entry from localhost. 

However, there is an issue when I deploy the application to the cloud. 

As soon as "gcloud app deploy" is executed I am getting following response:

------------------------------------------------------
Updating service [default]...failed.
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:
 '[' -n '' ']'
 NGINX_CONF_INCLUDE=/app/nginx-app.conf
 '[' -n '' ']'
 NGINX_CONF_OVERRIDE=/app/nginx.conf
 '[' -f /app/nginx-app.conf ']'
 mv /app/nginx-app.conf /etc/nginx/conf.d
 '[' -f /app/nginx.conf ']'
 '[' -n '' ']'
 PHP_FPM_CONF_OVERRIDE=/app/php-fpm.conf
 '[' -f /app/php-fpm.conf ']'
 '[' -n '' ']'
 PHP_INI_OVERRIDE=/app/php.ini
 '[' -f /app/php.ini ']'
 mv /app/php.ini /opt/php/lib/conf.d
 '[' -n '' ']'
 SUPERVISORD_CONF_ADDITION=/app/additional-supervisord.conf
 '[' -n '' ']'
 SUPERVISORD_CONF_OVERRIDE=/app/supervisord.conf
 '[' -f /app/additional-supervisord.conf ']'
 '[' -f /app/supervisord.conf ']'
 '[' -n '' ']'
 '[' -z appweb ']'
 sed -i 's|%%DOC_ROOT%%|appweb|g' /opt/nginx/conf/nginx.conf
 sed -i 's|%%DOC_ROOT%%|appweb|g' /opt/php/lib/php.ini
 /opt/php/bin/php /whitelist_functions.php
 '[' -f /app/composer.json ']'
 grep -q post-deploy-cmd
 su www-data -c 'php /usr/local/bin/composer --no-ansi run-script -l'
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/php56/lib/php/ex
tensions/no-debug-non-zts-20131226/memcached.so' - /opt/php56/lib/php/extensions
/no-debug-non-zts-20131226/memcached.so: cannot open shared object file: No such
 file or directory in Unknown on line 0
 chown -R root.www-data appweb
chown: cannot access 'appweb': No such file or directory   
------------------------------------------------------------------------------------------

Is there any setting has to be configured in the dashboard OR any changes in .yaml?

**Comment by tmatsuo** [comment]
Sorry for the late reply. The latest gcloud sdk should have a fix for this. Please update the gcloud sdk to the latest version and try deploying. Please let us know if you still have the issue.

```
gcloud components update
```
