### ISSUE TITLE
Can't deploy hello world on windows

### ISSUE THREAD

**Issue by moneal** [GoogleCloudPlatform/getting-started-php#153]
It appears that its having issues with docker setting the document root folder from app.yaml. For example cloning and deploying the code from `https://github.com/GoogleCloudPlatform/getting-started-php/tree/master/1-hello-world` returns this error: 

```
Updating service [default]...failed.
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:
+ '[' -n '' ']'
+ NGINX_CONF_INCLUDE=/app/nginx-app.conf
+ '[' -n '' ']'
+ NGINX_CONF_OVERRIDE=/app/nginx.conf
+ '[' -f /app/nginx-app.conf ']'
+ mv /app/nginx-app.conf /etc/nginx/conf.d
+ '[' -f /app/nginx.conf ']'
+ '[' -n '' ']'
+ PHP_FPM_CONF_OVERRIDE=/app/php-fpm.conf
+ '[' -f /app/php-fpm.conf ']'
+ '[' -n '' ']'
+ PHP_INI_OVERRIDE=/app/php.ini
+ '[' -f /app/php.ini ']'
+ '[' -n '' ']'
+ SUPERVISORD_CONF_ADDITION=/app/additional-supervisord.conf
+ '[' -n '' ']'
+ SUPERVISORD_CONF_OVERRIDE=/app/supervisord.conf
+ '[' -f /app/additional-supervisord.conf ']'
+ '[' -f /app/supervisord.conf ']'
+ '[' -n '' ']'
+ '[' -z appweb ']'
+ sed -i 's|%%DOC_ROOT%%|appweb|g' /opt/nginx/conf/nginx.conf
+ '[' -f /app/composer.json ']'
+ grep -q post-deploy-cmd
+ su www-data -c 'php /usr/local/bin/composer --no-ansi run-script -l'
+ chown -R root.www-data appweb
chown: cannot access 'appweb': No such file or directory
```

It works fine on a mac. No changes have been made to the cloned code and just trying to run `gcloud app deploy --no-promote --version hellotest`

Google Cloud SDK 140.0.0
beta 2016.01.12
bq 2.0.24
bq-win 2.0.24
bundled-python 2.7.10
core 2017.01.17
core-win 2016.11.07
gcloud
gsutil 4.22
gsutil-win 4.20
powershell 1.0.0.1
windows-ssh-tools 2016.05.13

**Comment by tmatsuo** [comment]
Thanks for reporting. I think this is the same issue as #152 
Sorry about this. We'll look into it.

**Comment by moneal** [comment]
Just as a note, I'm not seeing any error with the memcached extension like #152. The code deploys on my mac, both hello world and structured data examples.

**Comment by tmatsuo** [comment]
@moneal Sorry for the late reply. The latest gcloud sdk should have a fix for this. Please upgrade the gcloud sdk to the latest and try again. Let us know if you still have the problem.

```
gcloud components update
```
