### ISSUE TITLE
Add psrBatchLogger to logging step

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/getting-started-php#166]
https://cloud.google.com/php/getting-started/logging-application-events

We should show how to use psrBatchLogger here!

**Comment by bshaffer** [comment]
FYI @tmatsuo @ryanmats

**Comment by tmatsuo** [comment]
@bshaffer Are you still working on this?

**Comment by bshaffer** [comment]
Closing as this has been added to [the new bookshelf](https://cloud.google.com/php/getting-started/)
