### ISSUE TITLE
Composer Modules

### ISSUE THREAD

**Issue by JamesVanWaza** [GoogleCloudPlatform/getting-started-php#174]
Some `guzzle` packages have been abandoned, update to use the guzzle/guzzle instead. See Screenshot. 

This happened when I was following steps for Chapter 6-pubsub after running `composer install`

<img width="904" alt="screen shot 2018-01-04 at 10 46 52 am" src="https://user-images.githubusercontent.com/4000076/34571480-aa801328-f13c-11e7-8136-eec9e768ee7e.png">

**Comment by JamesVanWaza** [comment]
@bshaffer 
> Some `guzzle` packages have been abandoned, update to use the guzzle/guzzle instead. See Screenshot.
> 
> This happened when I was following steps for Chapter 6-pubsub after running `composer install`
> 
> <img alt="screen shot 2018-01-04 at 10 46 52 am" width="904" src="https://user-images.githubusercontent.com/4000076/34571480-aa801328-f13c-11e7-8136-eec9e768ee7e.png">

**Comment by bshaffer** [comment]
Try updating to `cboden/ratchet:0.4.1` to resolve these warnings.

The [new bookshelf](https://cloud.google.com/php/getting-started/) does not get these errors, as it does not require `cboden/ratchet`. `silex/silex` is also abandoned, but we are no longer updating those tutorials.

**Comment by bshaffer** [comment]
The PubSub tutorial is being replaced with the [Background Processing tutorial](https://github.com/GoogleCloudPlatform/getting-started-php/pull/210), so this can be closed.
