### ISSUE TITLE
incorrect $bucketname value set in the optional-compute-engine section

### ISSUE THREAD

**Issue by ramblescout** [GoogleCloudPlatform/getting-started-php#177]
RE:  getting-started-php/optional-compute-engine/src/app.php
line 168
$bucketName = $projectId . '.appspot.com';

.appspot.com is probably for AppEngine so for Compute Engine use:

$bucketName = $projectId;

**Comment by bshaffer** [comment]
This tutorial has been replaced by the new [getting started on compute engine](https://cloud.google.com/php/tutorials/getting-started-on-compute-engine) tutorial. Please use this instead.
