### ISSUE TITLE
books/delete throws an exception

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/getting-started-php#182]
PHP message: [2018-01-11 21:15:43] myapp.CRITICAL: Google\Cloud\Core\Exception\NotFoundException: { "error": { "errors": [ { "domain": "global", "reason": "notFound", "message": "Not Found" } ], "code": 404, "message": "Not Found" } } (uncaught exception) at /app/vendor/google/cloud/src/Core/RequestWrapper.php line 257 {"exception":"[object] (Google\\Cloud\\Core\\Exception\\NotFoundException(code: 404): {\n \"error\": {\n \"errors\": [\n {\n \"domain\": \"global\",\n \"reason\": \"notFound\",\n \"message\": \"Not Found\"\n }\n ],\n \"code\": 404,\n \"message\": \"Not Found\"\n }\n}\n at /app/vendor/google/cloud/src/Core/RequestWrapper.php:257)"} []

I suspect this is because the code is trying to delete the image_url in an assumption that the file is in cloud storage, however, we use the URL from the books API as it is.

**Comment by tmatsuo** [comment]
Ok, looks like there are two cases for the image_url. The first one is that a user upload the book cover image manually when creating a book entry, the other case is the pubsub worker add a thumbnail from the result of the Books API.

It seems like books/delete fails for the latter case.

**Comment by tmatsuo** [comment]
Nah. It fails for the former case too.

**Comment by tmatsuo** [comment]
Seems like this commit:
https://github.com/GoogleCloudPlatform/getting-started-php/commit/e3745a918b14aa7dc57f6994023ed2b7c628a1e8

is adding the code in question.

@bshaffer Can you look into this?

**Comment by bshaffer** [comment]
Yes I can take a look

**Comment by bshaffer** [comment]
The [new bookshelf](https://cloud.google.com/php/getting-started/) uses Firestore, so this is no longer an issue.
