### ISSUE TITLE
[6-pubsub] The health check handler is slow

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/getting-started-php#183]
The health check handler for the pubsub worker is slow to respond and thus the health check often fails with the default health check configuration (timeout=4secs).

I presume this is because the application initializes the connection to Cloud SQL at startup and also issue an SQL query for creating the table.

**Comment by tmatsuo** [comment]
@bshaffer Can you take a look?

**Comment by bshaffer** [comment]
The PubSub tutorial will be replaced with the [Background Processing tutorial](https://github.com/GoogleCloudPlatform/getting-started-php/pull/210), so we can close this now.
