### ISSUE TITLE
Changing MySQL from VARCHAR to DATE 

### ISSUE THREAD

**Issue by JamesVanWaza** [GoogleCloudPlatform/getting-started-php#186]
@bshaffer 
@tmatsuo 
In https://github.com/GoogleCloudPlatform/getting-started-php/blob/master/2-structured-data/src/DataModel/Sql.php, line 45 we can change the `VARCHAR` to `DATE` so that the actual date can show for published date. 

See my pull request below https://github.com/GoogleCloudPlatform/getting-started-php/pull/184/files

**Comment by bshaffer** [comment]
Closing as [the new bookshelf](https://cloud.google.com/php/getting-started/) uses firestore instead of Cloud SQL, and the docs for connecting to Cloud SQL for PHP [have been moved](https://cloud.google.com/sql/docs/mysql/connect-external-app#php)
