### ISSUE TITLE
How to Force SSL on Google App Engine Flexible Environment - PHP

### ISSUE THREAD

**Issue by JamesVanWaza** [GoogleCloudPlatform/getting-started-php#189]
Is there documentation showing how to force HTTPS on Google App Engine - Flexible PHP?

I tried placing secure on app.yaml and I had no luck.

I also tried in the nginx-app.conf placing this but no luck.

I also tried

    set $test "";

    if ($http_x_forwarded_proto = 'http') {
          set $test "http";
    }

    if ($test = 'http-non-cron') {
          return 301 https://$host$request_uri;
    }

Other Option I tried

```
<?php 

header("Strict-Transport-Security: max-age=31536000; includeSubDomains; preload");  
exit();

?>

but no luck.

**Comment by cesardmoro** [comment]
im Having the same issue, you solve it ? @JamesVanWaza

**Comment by FireBox1337** [comment]
Adding these lines to the nginx-app.conf file solved this issue:

```
if ($http_x_forwarded_proto = 'http') {
    set $test "http";
}

if ($test = 'http') {
    return 301 https://$host$request_uri;
}
```

**Comment by Gideon-Felt** [comment]
I'm having the same issue in a flexible environment using node, would this same fix apply?
