### ISSUE TITLE
Vendor Folder Missing

### ISSUE THREAD

**Issue by FrankBirdseye** [GoogleCloudPlatform/getting-started-php#202]
I'm following the bookshelf app example on GCP docs in PHP.

Under the getting-started-php/2-structured-data/web/index.php requires files from vendor folder which doesn't exists.

**Comment by lurkie** [comment]
Hi Frank,
Did you run `composer install` to download and install the required packages?

**Comment by FrankBirdseye** [comment]
Hey, thanks for the response. Yes but it didn't work at the time. I've managed to figure it out since.

**Comment by lurkie** [comment]
Nice! Then I think this issue can be closed.

Can you share any specifics on what went wrong?

**Comment by FrankBirdseye** [comment]
Certainly.

Not exactly, I went back through the tutorial (on GCP) and redid the steps.
