### ISSUE TITLE
PHPstorm cant resolve objects

### ISSUE THREAD

**Issue by lurkie** [GoogleCloudPlatform/getting-started-php#203]
In several files (mostly controllers.php), the PHPdoc annotations need a leading backslash in order to let PHPstorm resolve the classes. For example:

```php
/** @var Twig_Environment $twig */
/** @var Symfony\Component\HttpFoundation\Session\Session $session */
```

whould become

```php
/** @var \Twig_Environment $twig */
/** @var \Symfony\Component\HttpFoundation\Session\Session $session */
```
Among a few other PHPdoc changes.
I'm willing to provide a patch, if this issue is going to be accepted.

**Comment by bshaffer** [comment]
These PHPDoc annotations no longer exist.
