### ISSUE TITLE
Can't deploy?

### ISSUE THREAD

**Issue by cdcline** [GoogleCloudPlatform/getting-started-php#247]
I'm not sure what I'm doing wrong.

Recently (over the past week) I've been getting an error deploying to the gcloud:
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/1248182/177409456-f72bf886-33d9-43ac-a840-1a1b6768b354.png">

I've tried several ways of fixing it, even the [firestore specific](https://github.com/googleapis/google-cloud-php-firestore/blob/main/composer.json) configuration and can't get it to deploy with `ext-grpc`.

I'm sure this worked a month or so ago because I was deploying; it is a recent change to gcloud.

I'll also note, when you install this program you get a warning
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/1248182/177410039-865bb7f6-93f5-4e24-99e0-b72d0f831a6d.png">

It seems pretty silly for demo code to be outdated. Is there someplace else I should be looking for PHP examples? Is PHP getting unsupported?

**Comment by cdcline** [comment]
Seems to be working now. I assume there was some issue with the gcloud machine bootup :/

Still has the PHP 7.3 warning. Would be nice it the demo code wasn't complaining about unsupported code.

**Comment by bshaffer** [comment]
Hi @cdcline! We have a runtime out for PHP 8.1, so if you'd like, you can change `runtime: php73` to `runtime: php81` in your `app.yaml` to remove the warning.

**Comment by cdcline** [comment]
@bshaffer I'm still having issues:

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/1248182/178384387-bf1ff180-e848-4071-9c3b-5a4d1431aefc.png">

are you expecting me to do composer stuff too?

I was initially able to just clone it into the Google Shell and `gcloud deploy` but now I get all these errors.

**Comment by bshaffer** [comment]
This repo hasn't been updated for some time, so it's not compatible with PHP 8.1 in it's current state. Sorry for the incorrect advice. We would need to update the dependencies and code for it to run on PHP 8.1
