### ISSUE TITLE
feature: support cloud run deployment for bookshelf demo app

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/getting-started-php#253]
To support deployment to Cloud Run, let's get a Dockerfile for the bookshelf app OR allow deploying as buildpack. 

Reference from other getting started apps (added Dockerfile):
- [Node.js](https://github.com/GoogleCloudPlatform/nodejs-getting-started/pull/551) 
- [Python](https://github.com/GoogleCloudPlatform/getting-started-python/pull/486)

**Comment by vishwarajanand** [comment]
May take reference from this:
https://github.com/googleapis/testing-infra-docker/blob/main/php/php80/Dockerfile

**Comment by vishwarajanand** [comment]
@rogerthatdev  do you want to take this up or you want help?

**Comment by rogerthatdev** [comment]
In lieu of adding a Dockerfile, i've submitted #254 to support deploying as buildpack instead.
