### ISSUE TITLE
Invalid perameter in method docblock

### ISSUE THREAD

**Issue by piotrekkr** [GoogleCloudPlatform/getting-started-php#258]
https://github.com/GoogleCloudPlatform/getting-started-php/blob/5a68b1d9853c751274884482a16e2c7c0a16fdef/authenticate-users/index.php#L27

Contains invalid parameter in docblock. Should be `$idToken`

**Comment by bshaffer** [comment]
Fixed!

**Comment by bshaffer** [comment]
https://github.com/GoogleCloudPlatform/getting-started-php/commit/4491477cce4b8a999fb95a4e4a6b9fc609acb77d

**Comment by piotrekkr** [comment]
@bshaffer tbh I think you may also need to check if description is correct. It made sense with `$assertion` but not sure about `$idToken`.

**Comment by bshaffer** [comment]
It's fine. "The JWT string to assert"  can describe an ID token.
