### ISSUE TITLE
Use silex sessions instead of raw cookies

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/getting-started-php#41]
We should use the silex [session handler](http://silex.sensiolabs.org/doc/providers/session.html) instead of setting raw cookies, in order to rely on PHP's native sessions, thus benefitting from the abounding goodness and prosperity which is sure to follow.

**Comment by tmatsuo** [comment]
FYI: https://github.com/GoogleCloudPlatform/php-docker/pull/48 will enable PHP's memcached based session by default. According to http://silex.sensiolabs.org/doc/providers/session.html, I think you should do the following:

```php
$app['session.storage.handler'] = null;
```

**Comment by bshaffer** [comment]
Aha, yes, sounds good. Let's wait until we have the container ready before making that change, so we can test the results. With some quick testing, I found this does not seem to impact running the session in the local environment, but I'd like to test more to be sure.

**Comment by tmatsuo** [comment]
I think I can close this

**Comment by bshaffer** [comment]
yep! Thanks
