### ISSUE TITLE
Hello world bug

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/getting-started-php#71]
When following the guide and running hello world, I get this in the browser:

Warning: DateTime::createFromFormat(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/beckwith/Code/getting-started-php/1-hello-world/vendor/symfony/http-foundation/Response.php on line 331
Hello World

**Comment by bshaffer** [comment]
This is an issue when you set up PHP for the first time, and is not related to the getting started app. More info [here](http://stackoverflow.com/questions/2213608/php-configuration-it-is-not-safe-to-rely-on-the-systems-timezone-settings)
