### ISSUE TITLE
phpseclib "phpinfo" is causing execution to fail on Managed VMs

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/getting-started-php#85]
The `phpseclib` library used to validate ID Tokens is [calling phpinfo to determine the OpenSSL version](https://github.com/phpseclib/phpseclib/blob/2.0.1/phpseclib/Math/BigInteger.php#L267). Because `phpinfo` is blacklisted by `suhosin`, it will not run without special whitelisting in the Managed VMs environment.

Relevant Error:

```
# cat  /var/log/app_engine/suhosin.log    
Feb  8 19:45:53 [18] ALERT - function within blacklist called: phpinfo() (attacker '169.254.160.2', file '/app/vendor/google/apiclient/src/Goo
gle/AccessToken/Verify.php', line 78)
Feb  8 19:46:14 [18] ALERT - function within blacklist called: phpinfo() (attacker '169.254.160.2', file '/app/vendor/google/apiclient/src/Goo
gle/AccessToken/Verify.php', line 78)
```

**Comment by bshaffer** [comment]
fix: https://github.com/google/google-api-php-client/pull/848

**Comment by tmatsuo** [comment]
@bshaffer Great, can you create a release tag on that repo so that we can have them?

**Comment by bshaffer** [comment]
@tmatsuo we should just update `google-api-php-client` to a @dev tag for now. RC tags on that library should not be a result of this repo's requirements :-/

**Comment by bshaffer** [comment]
fixed - updating to stable version is tracked in #98
