### ISSUE TITLE
Bookshelf Cloud SQL app doesn't deploy.

### ISSUE THREAD

**Issue by Steve53** [GoogleCloudPlatform/getting-started-php#9]
The Bookshelf app does not yet have app.yaml or Dockerfile.

I tried this:
   Create a Cloud SQL instance and database in my project.
   Copy Dockerfile from Helloworld to Bookshelf.
   Copy app.yaml from Helloworld to Bookshelf.
   Add three environment variables to app.yaml:
      env_variables:
         MYSQL_DSN: 'mysql:host=173.194.83.205;dbname=books'
         MYSQL_USER: phpapp
         MYSQL_PASSWORD: steve

   gcloud preview app deploy app.yaml --promote

   The deployment seems to succeed:
      Deployed module [default] to [https://steve-44.appspot.com]

When I go to https://steve-44.appspot.com, I get a 404.
Last week when I did a similar experiment I got a 500.

**Comment by tmatsuo** [comment]
Thanks for reporting. I'll look into this.

**Comment by tmatsuo** [comment]
As you may already noticed, this repo is still working in progress though.

**Comment by tmatsuo** [comment]
I will shortly add app.yaml, Dockerfile and nginx-app.conf to the repo.

(If you copy nginx-app.conf too, it should work :)

**Comment by tmatsuo** [comment]
You also need to set GOOGLE_STORAGE_BUCKET envvar.

**Comment by tmatsuo** [comment]
Oh there is one more file you need to add...

Anyways, I will create a pull request tomorrow.

**Comment by tmatsuo** [comment]
I added some files in #11 although it's WIP, you can see what files are needed.
