### ISSUE TITLE
Handle flaky tests

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/getting-started-php#93]

**Comment by tmatsuo** [comment]
- Retry datastore test
- Retry gcloud installation if it failed

**Comment by bshaffer** [comment]
Can this be closed? We added retry for datastore. 

For `gcloud` we can break the [gcloud installation part](https://github.com/GoogleCloudPlatform/getting-started-php/blob/master/testing/install_test_dependencies.sh#L71) into it's own script and do `travis_retry` when we install.

**Comment by tmatsuo** [comment]
I will close this when gcloud installation retry is implemented
